#For UI Testing
url = https://www.saucedemo.com
browser = chrome
validUserName = standard_user
validPassword = secret_sauce

#For API Testing
base.api.url=https://reqres.in
api.key=reqres-free-v1
register.endpoint=/api/register
get.user.endpoint=/api/users/{id}